### ISSUE TITLE
Creating a package with a space in the name has odd behavior.

### ISSUE THREAD

**Issue by Zoltu** [atom/package-generator#23]
Create a new package with a space in the name.  Notice how throughout the project the name retains the space but the casing is normalized (lower) and a hyphen is added as a postfix after the space.

Example:
Package name: `Foo Bar`
Result: `foo -bar`

**Comment by thomasjo** [comment]
This is not supported. Words in package names should be separated with hyphens. None of the infrastructure (AFAIK) supports spaces the way the specified package name is used, including GitHub itself where the package name is used in an example repo URL. Package names are *humanized* in the places where it matters (almost nowhere); e.g. `foo-bar` would become "Foo Bar".

Not sure if this is documented anywhere, but seeing as we've never had any similar reports I can only guess it's either obvious, or that it's documented somewhere that I did not find right now.

**Comment by thomasjo** [comment]
This is also a duplicate of https://github.com/atom/package-generator/issues/17.

**Comment by Zoltu** [comment]
I believe there was a misunderstanding in my bug report.  The space is left in, a hyphen is added (next to the space).  In my example, `foo -bar` is `foo<space><hyphen>bar`.  I provided my feedback on #17, but that is a separate discussion.  Currently, name transformation is occurring but it is occurring incorrectly.

**Comment by izuzak** [comment]
@Zoltu The reason why you're seeing dashes in there is that names are [dasherized](https://github.com/atom/package-generator/blob/91bde1ec2a833ba71d7e6683727c2ae4278a8c1f/lib/package-generator-view.coffee#L66), which means that capital letters are replaced with a lowercase letter + `-` prefix. See [this](https://github.com/atom/underscore-plus/blob/2046d1562896761e3c38b7a647ac30b87b46ea20/src/underscore-plus.coffee#L83-L91).

For example:

```
> _.dasherize("AbCdEf")
> "ab-cd-ef"
```

In other words, you're seeing expected behavior here -- spaces are not the problem. Still, if you use spaces when generating a package, you will get a package.json which has `name` with spaces. And publishing such a package with apm will fail because apm will only accept packages with names `a-zA-Z0-9_-`. My opinion is that we should validate that in the input form and not allow creating packages with invalid names, and that's what issue #17 is about, I believe. 

I hope that helps and I think we should keep this issue closed as a duplicate of #17. Let me know if I'm misunderstanding your report as well.

**Comment by Zoltu** [comment]
Ah, that makes sense.  Thanks.
